apiVersion: ark.heptio.com/v1
kind: Schedule
metadata:
  name: prod-backup
  namespace: heptio-ark
spec:
  schedule: 0 1 * * *
  template:
    excludedNamespaces: null
    excludedResources: null
    hooks:
      resources: null
    includeClusterResources: null
    includedNamespaces:
    - '*'
    includedResources: null
    labelSelector:
      matchExpressions:
      - key: backup
        operator: NotIn
        values:
        - ignore
    ttl: 720h0m0s